#!/usr/bin/env python3
"""How common each English word is (decisions/0067, 2026-10-07): word => rank, 1 the most used.

Search uses it to finish a word still being typed ("new mus" is "new music", not the genus Mus): of the words that start
that way and lead somewhere, the commonest first. The rank is the word's row in the spaCy en_core_web_lg vectors (CC0),
which are stored most frequent first. Build machine only; the site reads the PHP file.

    python3 build_word_rank.py /path/to/en_core_web_lg-3.7.1 /path/to/site/api/lib/data/word-rank.php [limit]
"""
import re
import sys

import spacy


def main():
    model, out = sys.argv[1], sys.argv[2]
    limit = int(sys.argv[3]) if len(sys.argv) > 3 else 100000
    nlp = spacy.load(model, exclude=['tagger', 'parser', 'ner', 'lemmatizer', 'attribute_ruler', 'tok2vec', 'senter'])
    strings = nlp.vocab.strings
    rank = {}
    for key, row in sorted(nlp.vocab.vectors.key2row.items(), key=lambda kv: kv[1]):
        try:
            w = strings[key].lower()
        except KeyError:
            continue
        if not re.fullmatch(r"[a-z][a-z\-]*[a-z]", w) or w in rank:
            continue
        rank[w] = len(rank) + 1
        if len(rank) >= limit:
            break
    with open(out, 'w', encoding='utf-8') as f:
        f.write('<?php\n/* Generated by workers/lexicon/build_word_rank.py (decisions/0067): word => how common it is, 1 the most.\n'
                '   From the spaCy en_core_web_lg vectors (CC0). Do not edit. */\nreturn [')
        f.write(','.join("'%s'=>%d" % (w, r) for w, r in rank.items()))
        f.write('];\n')
    print(len(rank), 'words')


if __name__ == '__main__':
    main()
